const express=require('express')
const router =express.Router()

const multerMiddle = require('../middleware/multerMiddleware')
const jwtMiddle = require('../middleware/jwtMiddleware')

const user = require('../controllers/userController')
const post = require('../controllers/postControllers')
const comment = require('../controllers/commentControllers')
const message = require('../controllers/messageController')

router.post('/register',user.userRegister)
router.post('/login',user.userLogin)
router.post('/verifyOTP',user.verifyOTP)
router.post('/resendOTP',user.resendOTP)
router.get('/search/:search',user.searchUser)
router.get('/getUser',jwtMiddle,user.getUser)
router.put('/editUser',jwtMiddle,multerMiddle.single('image'),user.editUser)
router.get('/getSpecificUser/:id',user.getSpecificUser)
router.get('/getUsers',jwtMiddle,user.getUsers)
router.post('/follow',jwtMiddle,user.followAndUnfollow)
router.post('/createPost',jwtMiddle,multerMiddle.single('image'),post.createPost)
router.get('/getFollowingPosts',jwtMiddle,post.getFollowingPosts)
router.get('/getSpecificUserPosts/:id',post.getSpecificUserPosts)
router.get('/getUserPosts',jwtMiddle,post.getUserPosts)
router.post('/likeAndUnlike/:id',jwtMiddle,post.likeAndUnlike)
router.get('/getAllPosts',post.getAllPosts)
router.put('/editPost/:id',jwtMiddle,multerMiddle.single('image'),post.editPost)
router.delete('/deletePost/:id',jwtMiddle,post.deletePost)
router.post('/createComment',jwtMiddle,comment.createComment)
router.get('/getComments/:id',comment.getComments)
router.get('/getFollowers',jwtMiddle,user.getFollowers)
router.get('/getFollowing',jwtMiddle,user.getFollowing)
router.post('/sendMessage/:id',jwtMiddle,message.sendMessage)
router.get('/getMessages/:id',jwtMiddle,message.getMessages)

module.exports =router